handled score extension images
openzim/mwoffliner pull request #1420
Opened 2021-03-26 14:31 UTC by MananJethwani

@kelson42 this resolves #1418

2021-03-26 14:34 UTC, MananJethwani commented
@kelson42 sorry I forgot about test please don't review yet

2021-03-26 14:49 UTC, MananJethwani commented
@kelson42 done.....I am using only `.png` in regex as it is mentioned [here](https://www.mediawiki.org/wiki/Extension:Score#:~:text=The%20Score%20extension%20allows%20the,into%20audio%20and%20MIDI%20files.) that this extension generates only png images

2021-03-26 18:16 UTC, kelson42 commented
@MananJethwani Code factor does not pass

2021-03-26 18:45 UTC, MananJethwani commented
@kelson42 please have a look now

2021-03-27 06:25 UTC, kelson42 requested changes
The problem of this PR is that score images are 0,0001% of all images, but mwoffliner checks them first, big waste of CPU.

2021-03-27 06:25 UTC, kelson42 commented on src/util/misc.ts
> +  parts = SCORE_IMAGE_URL_REGEX.exec(decodedUrl)
Missing semi colon

2021-03-27 06:25 UTC, kelson42 commented on src/util/misc.ts
> +  if(parts !== null){
Missing space

2021-03-27 09:43 UTC, MananJethwani commented
> The problem of this PR is that score images are 0,0001% of all images, but mwoffliner checks them first, big waste of CPU.

I would try to somehow merge the first 2 conditions to make this a bit faster I might have an idea....give me some time

2021-03-27 10:02 UTC, kelson42 commented
You should make the thumb regex more specific and put your score regex after

2021-03-27 12:32 UTC, MananJethwani commented
@kelson42 instead of moving it below thumb regex I could do something like this also
```
const len = 'https://upload.wikimedia.org/'.length;
str.indexOf('score/', len) === len;
```
or change the pattern only using
```
const pattern = str.includes('/score/') ? ... : ...;
```
if these are slow according to you I will go with your solution only of moving score regex down as conditional regex don't work in js

2021-03-27 12:35 UTC, kelson42 commented
No, do a proper regex please and don't test only the keyword "score".

2021-03-27 15:07 UTC, kelson42 approved these changes

2021-03-27 15:28 UTC, merged