changed video source for better resolution
openzim/mwoffliner pull request #1515
Opened 2021-08-05 18:37 UTC by MananJethwani

this fixes #1489

2021-08-05 21:49 UTC, kelson42 requested changes
What is the difference beetween `data-width` and `data-file-width`, it does not looks good to take both of them?

This should be tested with an automated test.

2021-08-05 21:49 UTC, kelson42 commented on src/util/saveArticles.ts
> +    const videoElArea = (videoEl.getAttribute('height') || 0) * (videoEl.getAttribute('width') || 0);
Here we need a comment explaining a bit the problem and the solution

2021-08-05 21:49 UTC, kelson42 commented on src/util/saveArticles.ts
> +    const videoElArea = (videoEl.getAttribute('height') || 0) * (videoEl.getAttribute('width') || 0);
I don't understand really the computation with width*heigth. Considering that all the videos have the same ratio (width/height), I think just comparing the widths should be enough.

2021-08-05 21:49 UTC, kelson42 commented on src/util/saveArticles.ts
>      sourcesToRemove.forEach(DU.deleteNode);
This is simply wrong, `sourcesToRemove` is not always defined.

2021-08-08 14:22 UTC, kelson42 requested changes
I think the whole approach can be simplified a lot:
* Remove `widthXHeightSorter` because we don't need that anymore as we don't take the small resolution anymore
* Just go through all the `source` node element and either keep the node (because this is a better choice than the previous) or remove it. At the end it should be only one left.
* I'm not even sure you need a dedicated function, so probably `videoSourceElement` could be deleted as well. If you want to isolate things in a dedicated function just create a function `videoSourceUrlPicker()` (current name `videoSourceElement` is pretty cryptic as well).

You should be able to do all of that in twice less lines than what we have today.... at least.

2021-08-09 11:27 UTC, kelson42 commented
@tim-moody Does it do the job properly now?

2021-08-09 15:41 UTC, tim-moody commented
@WikiDocJames and I will try to test.

2021-08-10 15:07 UTC, kelson42 approved these changes
LGTM now

2021-08-11 05:14 UTC, kelson42 commented
Will merge this PR, if a problem is still occuring, please open a new ticket.

2021-08-11 06:01 UTC, merged

2021-08-11 09:18 UTC, WikiDocJames commented
Okay we tested it 16 hours ago. But looks like you have just pushed the fix 3 hour ago. So will test again this am...

2021-08-11 12:32 UTC, tim-moody commented
@kelson42 I didn't notice that the changes weren't merged. Am I now to test with the latest docker image or a nightly or by building a branch?

2021-08-11 12:46 UTC, tim-moody commented
docker pull openzim/mwoffliner:latest says Image is up to date for openzim/mwoffliner:latest

2021-08-13 14:31 UTC, tim-moody commented
@kelson42 when do we expect this fix to be in the docker image?