Fixes to download articles thumbnails
openzim/mwoffliner pull request #1794
Opened 2023-02-23 21:10 UTC by pavel-karatsiuba

fixes: #1786

2023-02-24 07:27 UTC, kelson42 requested changes
Always put a PR description with:
* explanation about the problem (no code details)
* explanation about solution (no code details)
* impacts (for users, devs)

2023-02-25 20:47 UTC, kelson42 reviewed
The function handles many different details. The thumbnail is only one of them. I wonder why we need to handle the thumbnail in a special manner?!

2023-02-26 18:50 UTC, pavel-karatsiuba commented
In 2019 was added code with filtering of the details field in the response. After filtering the details contains only 'subCategories', 'revisions', and 'redirects' fields and in some cases can be also 'thumbnail' and others.
But then the code was changed. And the 'thumbnail' option was removed from the response.

I returned the 'thumbnail' option to the details response. I made fixes with minimum impact to not touch other functionality.

Maybe right now we also have a problem with other fields which were removed from the response: 'coordinates' and 'categories'.

2023-03-01 11:05 UTC, kelson42 commented
@pavel-karatsiuba Thank you for the explanation. Actually this is not the first time we have a problem around this (not all options been "continued"). This is a serious problem because the impact is really subtil and we don't see it immediatly. Please work on this PR so all details requested are automatically continued and that we won't create a new problem by adding or removing or renaming one of this detail.

I'm also concerned by the memory usage of the retrieving of these image URL (representing an article) because:
* We download it for all articles (even if we need less than 100 of them on the welcome page)
* I suspect we download them even if we don't need them for a "tiled welcome page" (typically with a selection).

Therefore I believe we should isolate the retrieval of these image URL in a dedicated method (working similarly than the one you have modified) but which would:
* Be called only if we need a tiled welcome page
* Be run only to retrieve 100 pictures... and not on all articles

2023-03-02 18:04 UTC, pavel-karatsiuba commented
@kelson42 
This PR is not so impacting memory usage or script execution time. With this PR will be saved additional text fields to the details array.
Thumbnails are downloaded later, only in case we need a tiled home page. The script downloads not more than 100 thumbnails.

2023-03-03 12:15 UTC, kelson42 commented
> @kelson42 This PR is not so impacting memory usage or script execution time. 

I didn't say this is a problem with this PR, I said there is a concern about the memory usage regarding how we proceed. I don't have talked anytime about execution time/speed. Think about it like this. on WPEN, currently, we are retrieving a tile image URL for almost 7.000.000 articles (potentially), but in best case we use only 100 of them.... and actually most probably none of them! One URL is 100 bytes in average, so make 80x7.000.000 bytes=560MB. This is my concern.

>With this PR will be saved additional text fields to the details array. 

Yes, 

> Thumbnails are downloaded later, only in case we need a tiled home page. 

I don't have written about Thumbnails, I have written about "image URL".

> The script downloads not more than 100 thumbnails.

That was clear.

Please reconsider the problem and the solution "Therefore I believe we should isolate the retrieval of these image URL in a dedicated method"

2023-03-06 20:20 UTC, pavel-karatsiuba commented
URLs for images which you can see on the welcome page are built from thumbnails URL. So we don't have additional data for images in details object. Also, we have strict restrictions about retrieving thumbnail data with details. We are requesting thumbnail data only for 100 articles. So in response, we will get additional fields with thumbnail data only for 100 articles.
So make 80x100 bytes=8Kb.
This is not really true because we are executing parallel requests and for my 8core processor it is 8 parallel requests. And we are getting details for 50 articles by one request. This is 8*80*50=32Kb additional data.
Of course, I can fix this: I can execute a request for the first 100 articles, wait for it, and then continue executing. But this exception will look not really good and will save only some Kb of traffic.

I think this PR is fixing the bug from the ticket. I propose to create a new ticket if we need to make something else.

2023-03-06 21:13 UTC, kelson42 approved these changes

2023-03-06 21:13 UTC, merged