Fix nodet format option (partial impl)
openzim/mwoffliner pull request #1902
Opened 2023-09-08 12:19 UTC by VadimKovalenkoSNF

Fix https://github.com/openzim/mwoffliner/issues/1868 (partial impl)

2023-09-11 18:07 UTC, kelson42 requested changes
I failed to test it:
```
> mwoffliner@1.13.0 start
> ./node_modules/.bin/ts-node-esm ./src/cli.ts --adminEmail=kelson@kiwix.org --osTmpDir=/dev/shm --optimisationCacheUrl=http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=.........&secretAccessKey=....... --mwUrl=https://fr.wikipedia.org --format=nodet --articleList=Paris,Berlin --verbose --forceRender=VisualEditor

[log] [2023-09-11T18:06:54.692Z] Starting mwoffliner v1.13.0...
[info] [2023-09-11T18:06:54.715Z] Using custom flavour: no
[log] [2023-09-11T18:06:54.721Z] closing sanitize redis DB
[log] [2023-09-11T18:06:55.036Z] Successfully logged in S3
[log] [2023-09-11T18:06:55.042Z] Getting text direction...
[log] [2023-09-11T18:06:55.043Z] Getting site info...
[log] [2023-09-11T18:06:55.044Z] Getting sub-title...
[info] [2023-09-11T18:06:55.045Z] Downloading [https://fr.wikipedia.org/wiki/]
[info] [2023-09-11T18:06:55.047Z] Getting JSON from [https://fr.wikipedia.org/w/api.php?action=query&meta=siteinfo&format=json&formatversion=2&siprop=general%7Cnamespaces%7Cstatistics%7Cvariables%7Ccategory%7Cwikidesc]
[info] [2023-09-11T18:06:55.049Z] Downloading [https://fr.wikipedia.org/wiki/]
[log] [2023-09-11T18:06:55.305Z] Text direction is [ltr]
[info] [2023-09-11T18:06:55.305Z] Getting JSON from [https://fr.wikipedia.org/w/api.php?action=query&meta=siteinfo&format=json&formatversion=2]
[info] [2023-09-11T18:06:55.457Z] Downloading [https://fr.wikipedia.org/static/images/project-logos/frwiki.png]
[error] [2023-09-11T18:06:55.966Z] Failed to run mwoffliner after [2s]: {
	"stack": "Error: Input file is missing: ",
	"message": "Input file is missing: "
}
[error] [2023-09-11T18:06:55.966Z] 

**********

Input file is missing: 

**********

```

2023-09-12 09:08 UTC, VadimKovalenkoSNF commented
@kelson42 
> -forceRender=VisualEditor
fr wiki doesn't support VisualEditor, I got `Cannot create an instance of VisualEditor renderer.` in my logs.

2023-09-12 11:41 UTC, VadimKovalenkoSNF commented
> I really wonder about that because VE is activated on all WPs AFAIK?! 

Yes, you're right. After additional debug I found that error occurred because of encoded characters in URL in the French wiki when checking capabilities.
> Why i don't have a proper error?

I reproduced your entire command and also got error `Input file is missing:`. This happened not because VisualRenderer (I removed it from CLI params) but because of problems with `--optimisationCacheUrl`. This error occurs for both En and Fr wiki, it doesn't suppose rely on renderer
> Why this is not check at start with proper exit?

Because capabilities check happens after S3 and Downloader instantiation. This is definitely something with S3. My previous comment was about French wiki and VisualEditor, because I didn't expect to get any other error, so I didn't include  `--optimisationCacheUrl` param to the URL.

2023-09-12 12:05 UTC, VadimKovalenkoSNF commented
Upd: error with `Input file is missing:` happened right after [migration](https://github.com/openzim/mwoffliner/pull/1865) to awd-sdk v3.

2023-09-12 13:13 UTC, VadimKovalenkoSNF commented on src/util/mw-api.ts
> +    const resp = await axios.get(decodeURI(url), { maxRedirects: 0, headers: { cookie: loginCookie } })
Decoding URL should help to avoid problems with querying to MW Action API for different foreign wikis.

2023-09-13 18:56 UTC, kelson42 commented
Hard to test without having #1904 first fixed.

2023-09-14 18:39 UTC, kelson42 requested changes
I have tested with `--mwUrl="https://fr.wikipedia.org" --format=nodet --verbose --articleList="Berlin,Paris" --forceRender=VisualEditor`. Paris article is OK but suprisingly Berlin is not.

Work as expected with `WikimediaDesktop` but not really with `VisualEditor` render. I expect such PR to integrate automated tests on all supported end-points systematicaly.

2023-09-15 15:04 UTC, VadimKovalenkoSNF commented
> Work as expected with WikimediaDesktop but not really with VisualEditor render

I could not reproduce it on the rebased version of this patch, works as expected on my side (both articles scraped correctly). If you face this issue again, please give me logs.

> I expect such PR to integrate automated tests on all supported end-points systematically.

There is a dedicated [test](https://github.com/openzim/mwoffliner/pull/1902/files#diff-8dc3073e26ab6fbbd6354798464a32fa777588212b918693f64c9693fb7b43dfR82) for VE and nodet

2023-09-20 17:55 UTC, kelson42 approved these changes
No it works?! So LGTM, but the test will have to be rewritten in an appropriate manner, so much code duplication is NOK

2023-09-20 17:55 UTC, merged